# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
