# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 05:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', django.contrib.postgres.fields.jsonb.JSONField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='story.Story')),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
