# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20160820_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story'),
        ),
    ]
