# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20160820_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
