# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_time',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
